version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
  kibana:
    image: kibana
    ports:
      - 5601:5601
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
    command: ["start-notebook.sh", "--NotebookApp.password='sha1:b9f6287f2504:e9ff0e9a65a0df2dce1261e698a3b595600bcbca'"] # sets notebook password to "qwerqwer"